server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: veiculo-service
          uri: "lb://VEICULO-SERVICE"
          predicates:
            - Path=/api/veiculo/**
          filters:
            - StripPrefix=2

        - id: aluguel-service
          uri: "lb://ALUGUEL-SERVICE"
          predicates:
            - Path=/api/aluguel/**
          filters:
            - StripPrefix=2
    discovery:
      enabled: true
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
springdoc:
  use-management-port: true
management:
  server:
    port: 9090
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0