server:
  port: 8080
spring:
  application:
    name: VEICULO-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  pattern:
    level: 5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
